workflows:
  capacitor_ios_online_unsigned:
    name: "Capacitor iOS (online, unsigned for Sideloadly)"
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      xcode: 15.4
      cocoapods: default
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        DERIVED_DATA: $CM_BUILD_DIR/xcodebuild
        APP_OUT: $CM_BUILD_DIR/PocketBounty-unsigned.ipa

    scripts:
      - name: Install Node deps
        script: npm ci

      - name: Sync Capacitor (installs Pods)
        script: npx cap sync ios

      - name: Build .app without signing (to a fixed folder)
        script: |
          set -e

          # Clean & build to a known DerivedData path
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -derivedDataPath "$DERIVED_DATA" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            clean build

          # App should now be here:
          APP_PATH="$DERIVED_DATA/Build/Products/Release-iphoneos/App.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "❌ App.app not found at $APP_PATH"
            echo "Available products:"
            ls -R "$DERIVED_DATA/Build/Products" || true
            exit 1
          fi

          # Package into an unsigned IPA
          rm -rf Payload
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry "$APP_OUT" Payload
          echo "✅ Unsigned IPA at: $APP_OUT"

    artifacts:
      - $CM_BUILD_DIR/PocketBounty-unsigned.ipa
      - $CM_BUILD_DIR/xcodebuild/Build/Products/Release-iphoneos/**/*
