workflows:
  capacitor_ios_online:
    name: Capacitor iOS (online)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      xcode: 15.4
      cocoapods: default
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.pocketbounty.app

    scripts:
      - name: Install Node deps
        script: |
          npm ci

      - name: Sync Capacitor (installs Pods)
        script: |
          npx cap sync ios

      # Uses Codemagic's xcode-project helper to archive & export an .ipa.
      # Code signing will be provided by Codemagic (set in UI).
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/Archives/**/App.xcarchive

    publishing:
      email:
        recipients:
          - "stokes4738@gmail.com"
        notify:
          success: true
          failure: true
