workflows:
  capacitor_ios_online_unsigned:
    name: Capacitor iOS (online, unsigned for Sideloadly)
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      xcode: 15.4
      cocoapods: default
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App

    scripts:
      - name: Install Node deps
        script: npm ci

      - name: Sync Capacitor (installs Pods)
        script: npx cap sync ios

      - name: Build .app without signing
        script: |
          set -e
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
            build

          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name 'Build' -maxdepth 3 | head -n1)/Products/Release-iphoneos/App.app

          mkdir -p Payload
          cp -R "$APP_PATH" Payload/

          /usr/bin/zip -qry PocketBounty-unsigned.ipa Payload

    artifacts:
      - PocketBounty-unsigned.ipa
